# This is a basic workflow to help you get started with Actions

name: test_specified

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test_specified:
    continue-on-error: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # gyan.dev #############################
          - provider: "gyan.dev"

          - provider: "gyan.dev"
            version: "4.4"

          - provider: "gyan.dev"
            version: "4.3.2"

          - provider: "gyan.dev"
            build_date: "2021-02-27"
          - provider: "gyan.dev"
            build_date: "2021-02-20"
          - provider: "gyan.dev"
            build_date: "2021-02-02"

          - provider: "gyan.dev"
            version: "4.3.2"
            build_date: "2021-02-27"
          - provider: "gyan.dev"
            version: "4.3.2"
            build_date: "2021-02-20"
          - provider: "gyan.dev"
            version: "4.3.2"
            build_date: "2021-02-02"

          # gyan.dev #############################
          - provider: "BtbN"

          - provider: "BtbN"
            version: "4.4"
          - provider: "BtbN"
            version: "4.3.2"
          - provider: "BtbN"
            version: "101947"

          - provider: "BtbN"
            commit_id: "gacb339bb88"
          - provider: "BtbN"
            commit_id: "g31d249a418"
          - provider: "BtbN"
            commit_id: "gc5ca18fd1b"

          - provider: "BtbN"
            version: "4.4"
            commit_id: "gacb339bb88"
          - provider: "BtbN"
            version: "4.3.2"
            commit_id: "g31d249a418"
          - provider: "BtbN"
            version: "101947"
            commit_id: "gc5ca18fd1b"
            ######################################

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: pzhlkj6612/actions-download-file@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          provider: ${{ matrix.provider }}
          filename_version: ${{ matrix.version }}
          filename_build_date: ${{ matrix.build_date }}
          filename_commit_id: ${{ matrix.commit_id }}

      - uses: pzhlkj6612/actions-download-file@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          provider: ${{ matrix.provider }}
          filename_version: ${{ matrix.version }}
          filename_build_date: ${{ matrix.build_date }}
          filename_commit_id: ${{ matrix.commit_id }}
          target: "./"

      - uses: pzhlkj6612/actions-download-file@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          provider: ${{ matrix.provider }}
          filename_version: ${{ matrix.version }}
          filename_build_date: ${{ matrix.build_date }}
          filename_commit_id: ${{ matrix.commit_id }}
          target: "../"

      - uses: pzhlkj6612/actions-download-file@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          provider: ${{ matrix.provider }}
          filename_version: ${{ matrix.version }}
          filename_build_date: ${{ matrix.build_date }}
          filename_commit_id: ${{ matrix.commit_id }}
          target: "./downloadFFMPEG/"

